### ISSUE TITLE
Selecting tabs (and other objects) impossible

### ISSUE THREAD

**Issue by eifeoh** [MH42/web-testing#1]
Navigating in logicaldocs seems to be impossible, as there seem to be no identifiers that would work with tabs. I.e. `driver.findElement(By.id("isc_3X")).click(); ` for navigating to "Documents" doesn't have any effect.

**Comment by MH42** [comment]
There is a new test ([NavigateTabsTest](https://github.com/MH42/web-testing/blob/master/src/seleniumtest/java/NavigateTabsTest.java) with a possible solution for this issue. 
Concerning dynamic id: if you don't find another solution, please use XPath. It's a rather bad choice, but at least it enables you to create tests.

**Comment by jstzb** [comment]
Some failing selenium ide tests have shown that even absolute and relative xpath dont work. In my setup the xpath of logout button changed
from :
//div[6]/div/table/tbody/tr/td/table/tbody/tr/td/img
To:
//div[5]/div/table/tbody/tr/td/table/tbody/tr/td/img
Only this xpath attribute stays same:
//img[contains(@src,'http://localhost:8080/frontend/sc/skins/Simplicity/images/actions/close.png')]

**Comment by MH42** [comment]
Both XPaths are the same apart from the leading div. Did you get a message from logicaldoc saying "You have new messages" at te top of the window? If yes, that's why the div changes as sonn as you close the message.
