### ISSUE TITLE
Login PageObject

### ISSUE THREAD

**Issue by jstzb** [MH42/web-testing#2]
Sorry for bringing this up, but some tests of mine seem to have trouble with Login PageObject. Its constructor changes the given Webdriver to a new FirefoxDriver instance. May i change this lines

`public LoginPage(WebDriver driver) {
        baseUrl = "http://localhost:8080";
  		driver = new FirefoxDriver();
        this.driver = driver;`

and change all tests accordingly?

**Comment by eifeoh** [comment]
Hi, sure you can.
