### ISSUE TITLE
Unable to locate "Save"-Button in AddDocument.java

### ISSUE THREAD

**Issue by eifeoh** [MH42/web-testing#3]
I tried all the ways I could think of to locate the "Save"-Button, but only got NoSuchElement or invisible and stale Exceptions. Not even unrecommended methods seem to work.

Those are the ways I tried:
`
//		driver.findElement(By.cssSelector("div[eventproxy*='isc_HLayout_'] div div"))
//					.click();	 //save file 
		
		//		    driver.findElement(By.cssSelector("div[eventproxy*='isc_Button_49'] table tbody"))
		//			.click();	 //save file 
		//		    driver.findElement(By.cssSelector("html body div#isc_DB.windowBackground div#isc_DK.windowBody div#isc_DL.normal div#isc_DM div#isc_F2.normal div#isc_F3 div#isc_F4 div#isc_F5"))
		//			.click();

		driver.findElement(By.xpath("/html/body/div[9]/div[2]/div/div/div[2]/div/div[1]/div/table/tbody/tr/td"))
		.click();

//		driver.findElement(By.name("Save")).click();
		// driver.findElement(By.id("isc_F5")).click();`

**Comment by jstzb** [comment]
```
driver.findElement(By.cssSelector("div[eventproxy^='isc_BulkUpdateDialog_'] div div div div div div table tbody tr td")).click();
```
did it for me once ^^

**Comment by eifeoh** [comment]
Great, worked for me once too. :)
