### ISSUE TITLE
Dependency on AddDocument

### ISSUE THREAD

**Issue by eifeoh** [MH42/web-testing#5]
Many tests rely on AddDocument.java - which fails at the moment, as the "Save" Button cannot be found. @jstzb could you change your tests to run with pre-uploaded files which could be restored with the repository? Then "RecoverLDState" could be run as `@BeforeClass` and the tests would no longer depend on the adding docs test.

**Comment by jstzb** [comment]
yes i will change my tests. recoverldstate still needs some work for me to work ;).
